[package]
name = "veta-gui"
description = "iced desktop interface for Veta."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
veta-core.workspace = true
iced.workspace = true

[lints]
workspace = true
